---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval = TRUE,message = FALSE,warning = FALSE)
```

# Getting Started

## Setting up R packages

To start with, [ggstatsplot](https://indrajeetpatil.github.io/ggstatsplot/) and tidyverse packages will be launched using library().


```{r}
packages = c('ggstatsplot','tidyverse','rstantools')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}
```


## Importing Data

```{r}
exam <- read_csv("Data/Exam_data.csv")
```

## Working with ggstatesplot

### ANOVA test

```{r fig.height=8,fig.width=6}
set.seed(1234)

ggbetweenstats(
  data = exam,
  x = RACE,
  y = ENGLISH,
  type = "bayes"
)
```









